name: flutter_learn_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  youtube_player_flutter: ^8.1.2
  percent_indicator: ^4.2.3
  hive_flutter:
  hive:
  path_provider:


dev_dependencies:
  flutter_test:
    sdk: flutter
  get:
  flutter_lints: ^2.0.0
  http: any
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - json/


